#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor LVDS1 -d 1 2 3 4 5
bspc monitor VGA1 -d 6 7 8 9 10

xsetroot -cursor_name left_ptr

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


sxhkd &
nitrogen --restore
picom &
dunst &

# Polybar
polybar -r left1 &
polybar -r mid1 &
polybar -r left-mid-1 &
polybar -r right-mid-1 &
polybar -r right1 &
polybar -r left2 &
polybar -r mid2 &
polybar -r right2 &

# Python Scripts
python3 ~/thewhistlerScripts/grihKaryaNotifs.py &

#AutoStart
/usr/lib/kdeconnectd &
kdeconnect-indicator &

