#!/bin/python3
import pyautogui as py
from glob import glob
import os
import datetime
import time
basePath = r"/home/thewhistler/Pictures/VedantuClassesScreenshot/"
i = input('''
Which Subject?
1. Physics
2. Maths
3. Chemistry
---> ''')
if i=="1":
    sub = "Physics"
elif i=="2":
    sub = "Maths"
elif i=="3":
    sub = "Chemistry"
else:
    exit()
i = input("Do you want to create a new folder? y/n")
if i=="y":
    name = input("Input Chapter Name: ")
    os.mkdir(basePath + sub + "/" + name)
    fPath = basePath + sub + "/" + name + "/"
else:
    dirs = glob(basePath + sub + "/*")
    j = 1
    for i in dirs:
        print(str(j) + " > " + i.replace(basePath + sub + "/", ""))
        j+=1
    i = input('''
    Which Chapter?
    --->''')
    fPath = dirs[int(i)-1] + "/"
while True:
    i = input("Press Enter to take a screenshot.")
    for i in range(1,1):
        print("Taking screenshot in {}".format(i))
        time.sleep(1)
    py.click(2253,223)
    name = str(datetime.datetime.now())[:-7]
    name = name.replace(" ","--")
    os.system("scrot -u {}".format(fPath+name)) 
    py.click(2253,223)
    py.click(1287,93)
    #py.screenshot(fPath + name)
